remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Power Outages and Hurricanes - A Data-Driven Study
description: Project for DSC80 at UCSD